# Generated by Django 4.0.2 on 2022-02-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestones',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
